### ISSUE TITLE
Images to PDF convertor

### ISSUE THREAD

**Issue by Kunal-Garg-12** [Kunal-Garg-12/Python-Scripts-Hacktoberfest-22#15]
Add a python script to convert a given set of images to a single PDF

**Comment by Prakhar9450** [comment]
Please assign me this task

**Comment by Kunal-Garg-12** [comment]
@Prakhar9450 Assigned

**Comment by Brotin003** [comment]
Can you please assign me to this task.

**Comment by Kunal-Garg-12** [comment]
@Brotin003 This issue has already been assigned. You can try to create a new unique issue and I will assign it to you

@Prakhar9450 If you are not working on this issue do let me know so I can assign this to someone else.

**Comment by Prakhar9450** [comment]
Please merge my pr #47
