### ISSUE TITLE
Convert text file to PDF file

### ISSUE THREAD

**Issue by Kunal-Garg-12** [Kunal-Garg-12/Python-Scripts-Hacktoberfest-22#2]
Add a python script to convert a text file to PDF file. You can use any library. Create a new appropriately named directory and add the script in it. Add an example case in the directory too. Make sure to read the contributing guidelines for this repo.

**Comment by Kunal-Garg-12** [comment]
@ElectricPlant19 Assigning this to you.

**Comment by ElectricPlant19** [comment]
> @ElectricPlant19 Assigning this to you.

I guess someone who was not assigned the issue has  added a contribution.
